name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer les dépendances
        run: composer install

      - name: Lancer les tests
        run: php bin/phpunit